//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBAIGUIXE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWHYSTORY
    {
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public string LicensePlate { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string DisplayName { get; set; }
        public string UserName { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
    }
}
